NeuroshimaHex.Web/Models/Game/GameEditViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NeuroshimaHex.Web.Models.Race;
using NeuroshimaHex.Web.Models.Team;
using NeuroshimaHex.Web.Models.User;

namespace NeuroshimaHex.Web.Models.Game
{
    public class GameEditViewModel
    {
        public Guid Id { get; set; }

        public Guid CreatorId { get; set; }

        [Display(Name = "Game Name")]
        [Required]
        public string Name { get; set; }

        [Display(Name = "Game Date")]
        public DateTime? GameTime { get; set; }

        public int GameUsersCount { get; set; }

        public bool IsFinished { get; set; }

        public List<TeamViewModel> Teams { get; set; }
        public List<UserViewModel> Users { get; set; }
        public List<RaceViewModel> Races { get; set; }
        public List<UsersInGameViewModel> UsersInGames { get; set; }
    }

}

NeuroshimaHex.Web/Models/Game/GameListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using NeuroshimaHex.Web.Models.Shared;

namespace NeuroshimaHex.Web.Models.Game
{
    public class GameListViewModel : SearchListViewModel<GameViewModel>
    {
    }
}

NeuroshimaHex.Web/Models/Game/GameViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace NeuroshimaHex.Web.Models.Game
{
    public class GameViewModel
    {
        public Guid Id { get; set; }

        public Guid CreatorId { get; set; }

        [Display(Name = "Game Name")]
        public string Name { get; set; }

        [Display(Name = "Game Date")]
        public DateTime GameTime { get; set; }

        public bool IsFinished { get; set; }
    }
}

NeuroshimaHex.Web/Models/Game/SetGameStatusViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using NeuroshimaHex.Web.Models.Team;

namespace NeuroshimaHex.Web.Models.Game
{
    public class SetGameStatusViewModel
    {
        public Guid Id { get; set; }

        public Guid CreatorId { get; set; }

        public DateTime? GameTime { get; set; }

        [Display(Name = "Game Name")]
        [Required]
        public string Name { get; set; }

        [Display(Name = "Is Finished")]
        [Required]
        public bool IsFinished { get; set; }

        [Display(Name = "Win Team")]
        [Required]
        public Guid WinsTeamGuid { get; set; }

        public List<TeamViewModel> Teams { get; set; }
    }
}

NeuroshimaHex.Web/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using NeuroshimaHex.Bll.Contracts.Services;
using NeuroshimaHex.Bll.Services.Identity;
using NeuroshimaHex.Domain.Entities;
using NeuroshimaHex.Domain.Objects.Query;
using NeuroshimaHex.Web.Models.Game;
using NeuroshimaHex.Web.Models.Race;
using NeuroshimaHex.Web.Models.Team;
using NeuroshimaHex.Web.Models.User;

namespace NeuroshimaHex.Web.Controllers
{
    public class GameController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IGameService _gameService;
        private readonly ITeamService _teamService;
        private readonly IUserService _userService;
        private readonly IRaceService _raceService;
        private readonly NeuroshimaHexUserManager _userManager;

        public GameController(IMapper mapper, IGameService gameService, ITeamService teamService, IUserService userService, IRaceService raceService, NeuroshimaHexUserManager userManager)
        {
            _mapper = mapper;
            _gameService = gameService;
            _teamService = teamService;
            _userService = userService;
            _userManager = userManager;
            _raceService = raceService;
        }

        public ActionResult Index(DateTime? dateFrom, DateTime? dateTo, string search = "", int page = 1, int length = 15)
        {
            var result = _gameService.GetGames(new SearchQuery
            {
                Orderby = new ColumnOrder
                {
                    Column = "Name",
                    Direction = SortDirection.Asc
                },
                Paging = new Paging
                {
                    Length = length,
                    Skip = (page - 1) * length,
                },
                Search = search,
                DateFrom = dateFrom,
                DateTo = dateTo
            });
            return View(new GameListViewModel()
            {
                Search = search,
                DateFrom = dateFrom,
                DateTo = dateTo,
                Page = page,
                RecordsFiltered = result.RecordsFiltered,
                RecordsTotal = result.RecordsTotal,
                PageNumber = result.RecordsFiltered / length + (result.RecordsFiltered % length > 0 ? 1 : 0),
                Records = result.Data.Select(x => _mapper.Map<GameViewModel>(x)).ToList()
            });
        }

        public ActionResult Create()
        {
            var model = new GameEditViewModel();
            model.Teams = new List<TeamViewModel>();
            ViewBag.DefaultTeamName = "Game #" + _gameService.GetGameCount();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(GameEditViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            model.Id = Guid.NewGuid();
            model.UsersInGames = new List<UsersInGameViewModel>();

            if (model.CreatorId == Guid.Empty)
            {
                model.CreatorId = _userManager.FindByNameAsync(User.Identity.Name).Result.Id;
            }

            var users = _userService.GetUsers();
            foreach (var team in model.Teams)
            {
                foreach (var teamUser in team.Users)
                {
                    var userInGame = new UsersInGameViewModel()
                    {
                        GameId = model.Id,
                        UserId = teamUser.Id,
                        RaceId = teamUser.Race.Id
                    };
                    //userInGame.Id = Guid.NewGuid();
                    model.UsersInGames.Add(userInGame);
                }
            }

            foreach (var team in model.Teams)
            {
                team.Id = new Guid();
                team.GameId = model.Id;
                team.TeammateCount = team.Users.Count;
            }

            var value = _mapper.Map<GameEditViewModel, Game>(model);
            foreach (var team in value.Teams)
            {
                var currentTeamUsers =
                    team.Users.Select(teamUser => teamUser.Id)
                        .Select(userId => users.Single(x => x.Id == userId))
                        .ToList();
                team.Users = currentTeamUsers;
            }
            _gameService.CreateGame(value);

            return RedirectToAction("Index");
        }

        public ActionResult Edit(Guid id)
        {
            var value = _gameService.GetGameById(id);
            var model = _mapper.Map<GameEditViewModel>(value);
            var races = _raceService.GetRaces();
            model.Races = _mapper.Map<List<RaceViewModel>>(races);
            var users = _userService.GetUsers();
            model.Users = _mapper.Map<List<UserViewModel>>(users);
            foreach (var teamViewModel in model.Teams)
            {
                foreach (var user in teamViewModel.Users)
                {
                    var userRaceId = model.UsersInGames.Single(u => u.UserId == user.Id).RaceId;
                    var racesListItem = model.Races.Select(r => new SelectListItem
                    {
                        Text = r.Name,
                        Value = r.Id.ToString(),
                        Selected = r.Id == userRaceId
                    }).ToList();
                    user.RacesSelectList = racesListItem;
                    var usersListItem = model.Users.Select(u => new SelectListItem
                    {
                        Text = u.FirstName + " " + u.LastName,
                        Value = u.Id.ToString(),
                        Selected = u.Id == user.Id
                    }).ToList();
                    user.UsersSelectList = usersListItem;
                }
            }
            return View("~/Views/Game/Edit.cshtml",model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(GameEditViewModel model)
        {
            var value = _gameService.GetGameById(model.Id);
            var listTeams = new List<Team>();
            foreach (var team in model.Teams)
            {
                listTeams.Add(new Team
                {
                    GameId = model.Id,
                    Id = team.Id,
                    TeamName = team.TeamName,
                    TeammateCount = team.TeammateCount

                });
                team.GameId = model.Id;
            }
            _teamService.UpdateTeam(listTeams);
            if (value != null)
            {
                value.GameTime = model.GameTime.Value;
                value.Name = model.Name;
                _gameService.UpdateGame(value);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Remove(GameEditViewModel model)
        {
            var value = _gameService.GetGameById(model.Id);
            if (value != null)
            {
                //_mapper.Map(model, value);
                _gameService.ToArchive(value);
            }
            return RedirectToAction("Index");
        }

        public ActionResult GameInfo(Guid id)
        {
            var value = _gameService.GetGameById(id);
            var model = _mapper.Map<GameEditViewModel>(value);
            var races = _raceService.GetRaces();
            model.Races = _mapper.Map<List<RaceViewModel>>(races);
            var users = _userService.GetUsers();
            model.Users = _mapper.Map<List<UserViewModel>>(users);

            return View("~/Views/Game/Info.cshtml", model);
        }

        public ActionResult SetGameStatus(Guid id)
        {
            var value = _gameService.GetGameById(id);
            var model = _mapper.Map<SetGameStatusViewModel>(value);

            return View("~/Views/Game/SetStatus.cshtml", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SetGameStatus(SetGameStatusViewModel model)
        {
            var value = _gameService.GetGameById(model.Id);
            value.Teams.Single(x => x.Id == model.WinsTeamGuid).IsWin = true;
            value.IsFinished = model.IsFinished;
            _gameService.UpdateGame(value);
            return RedirectToAction("Index");
        }


    }
}

NeuroshimaHex.Web/Controllers/TeamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using NeuroshimaHex.Bll.Contracts.Services;
using NeuroshimaHex.Bll.Services.Identity;
using NeuroshimaHex.Web.Models.Game;
using NeuroshimaHex.Web.Models.Race;
using NeuroshimaHex.Web.Models.Team;
using NeuroshimaHex.Web.Models.User;

namespace NeuroshimaHex.Web.Controllers
{
    public class TeamController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IUserService _userService;
        private readonly IRaceService _raceService;
        private readonly NeuroshimaHexUserManager _userManager;


        public TeamController(IMapper mapper, IUserService userService, IRaceService raceService, NeuroshimaHexUserManager userManager)
        {
            _mapper = mapper;
            _userService = userService;
            _userManager = userManager;
            _raceService = raceService;
        }

        public PartialViewResult CreateTeam(int teamCount = 2, int teammateCount = 2)
        {
            var model = new GameEditViewModel();
            model.Teams = new List<TeamViewModel>();
            var users = _userService.GetUsers();
            model.Users = _mapper.Map<List<UserViewModel>>(users);

            var usersCount = model.Users.Count;
            if (teamCount > usersCount)
            {
                teamCount = usersCount;
            }

            if (teammateCount * teamCount > usersCount)
            {
                teammateCount = usersCount / teamCount;
            }
            model.GameUsersCount = teamCount * teammateCount;
            var races = _raceService.GetRaces();
            model.Races = _mapper.Map<List<RaceViewModel>>(races);

            var defaultSelectItem = new SelectListItem { Text = "Select", Value = "0", Selected = true, Disabled = true };
            var racesListItem = model.Races.Select(r => new SelectListItem
            {
                Text = r.Name,
                Value = r.Id.ToString()
            }).ToList();
            racesListItem.Add(defaultSelectItem);

            var usersListItem = model.Users.Select(u => new SelectListItem
            {
                Text = u.FirstName + " " + u.LastName,
                Value = u.Id.ToString()
            }).ToList();
            usersListItem.Add(defaultSelectItem);


            for (var i = 0; i < teamCount; i++)
            {
                var team = new TeamViewModel();
                team.Users = new List<UserViewModel>();
                for (var j = 0; j < teammateCount; j++)
                {
                    team.TeamName = "Team #" + (i + 1);
                    team.Users.Add(new UserViewModel
                    {
                        RacesSelectList = racesListItem,
                        UsersSelectList = usersListItem
                    });
                }
                team.TeammateCount = teammateCount;
                model.Teams.Add(team);
            }
            model.UsersInGames = new List<UsersInGameViewModel>();

            return PartialView("~/Views/Team/_CommonTeamEdit.cshtml", model);
        }
    }
}

NeuroshimaHex.Web/Views/Game/Create.cshtml
@model NeuroshimaHex.Web.Models.Game.GameEditViewModel

@{
    ViewBag.Title = "Create Game";
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.PanelTitle = "Game";
    ViewBag.Heading = "Create Game";
}
<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <h3>@ViewBag.Title</h3>

        <div class="row">
            <div class="panel panel-section">
                <div class="panel-heading">
                    <h2 class="panel-title">@ViewBag.PanelTitle</h2>
                </div>
                <div class="panel-body">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                        @Html.Partial("_CommonEdit")
                    }
                </div>
            </div>
        </div>
    </div>
</div>

NeuroshimaHex.Web/Views/Game/Edit.cshtml
@model NeuroshimaHex.Web.Models.Game.GameEditViewModel

@{
    var title = "Edit Game";
    ViewBag.Title = title;
    Layout = "~/Views/Shared/_PaneledStyleLayout.cshtml";
    ViewBag.PanelTitle = "Game";
    ViewBag.Heading = title;
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.Partial("_CommonEdit")
}

NeuroshimaHex.Web/Views/Game/Index.cshtml
@using Microsoft.AspNet.Identity
@using NeuroshimaHex.Domain.Enums
@model NeuroshimaHex.Web.Models.Game.GameListViewModel
@{
    ViewBag.Title = "Gemes";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var userId = Guid.Parse(HttpContext.Current.User.Identity.GetUserId());
}

<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <div class="row">
            <h3>@ViewBag.Title</h3>

            <div>
                @Html.ActionLink("Add", "Create", null, new { @class = "btn btn-default", style = "float: left; display: inline-block; margin-top: 8px" })
            </div>

            <form class="navbar-form navbar-left" role="search">
                @Html.TextBoxFor(m => m.Search, new { @class = "form-control", placeholder = "Search" })
                <div class="form-group">
                    @Html.LabelFor(m => m.DateFrom, htmlAttributes: new { @class = "control-label " })
                    @Html.EditorFor(m => m.DateFrom, new { htmlAttributes = new { @id = "dateFrom", @class = "form-control" } })
                    @Html.LabelFor(m => m.DateTo, htmlAttributes: new { @class = "control-label " })
                    @Html.EditorFor(m => m.DateTo, new { htmlAttributes = new { @id = "dateTo", @class = "form-control" } })
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
            </form>
        </div>
        <div class="row">
            <div class="panel panel-section">
                <div class="panel-heading">
                    <h2 class="panel-title">List of Games</h2>
                </div>
                <div class="panel-body">
                    <table class="table table-striped table-bordered table-hover" style="margin-top: 15px;">
                        <tr>
                            <th>
                                @Html.DisplayName("Game Name")
                            </th>
                            <th>
                                @Html.DisplayName("Game Date")
                            </th>
                            <th>
                                @Html.DisplayName("Actions")
                            </th>
                        </tr>

                        @foreach (var item in Model.Records)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.GameTime)
                                </td>
                                <td>
                                    @if (item.CreatorId == userId || User.IsInRole(UserRoles.Admin))
                                    {
                                        @Html.ActionLink("Edit", "Edit", new {id = item.Id})
                                        @Html.Raw(" / ")
                                        @Html.ActionLink("Remove", "Remove", new {id = item.Id})
                                        @Html.Raw(" / ")
                                        if (!item.IsFinished && item.GameTime <= DateTime.Now)
                                        {
                                            @Html.ActionLink("Set Game Status", "SetGameStatus", new { id = item.Id })
                                            @Html.Raw(" / ")
                                        }
                                    }
                                    @Html.ActionLink("Game Info", "GameInfo", new { id = item.Id })
                                    
                                </td>
                            </tr>
                        }
                    </table>
                    @Html.Partial("~/Views/Shared/_PaginationPartial.cshtml", Model)
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(function () {
        $('#dateFrom').datetimepicker({});
        $('#dateTo').datetimepicker({});
    });
</script>

NeuroshimaHex.Web/Views/Game/Info.cshtml
@using NeuroshimaHex.Web.Models.Shared
@model NeuroshimaHex.Web.Models.Game.GameEditViewModel

@{
    var title = "Game Info";
    ViewBag.Title = title;
    Layout = "~/Views/Shared/_PaneledStyleLayout.cshtml";
    ViewBag.PanelTitle = "Game";
    ViewBag.Heading = title;
}

<div id="raceInfoContainer">

    @foreach (var team in Model.Teams)
    {
        <div class="panel panel-default col-md-6">
            <div class="panel-body ">
                <div class="form-group">
                    <label style="font-size: 30px;">@team.TeamName</label>
                </div>

                <div class="form-group">
                    <div class="col-md-12">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>User Name</th>
                                    <th>User Race</th>
                                    <th>Race Ico</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var user in team.Users)
                                {
                                    var userRaceId = Model.UsersInGames.Single(x => x.UserId == user.Id).RaceId;
                                    var userRace = Model.Races.Single(x => x.Id == userRaceId);
                                    var base64 = "" + Convert.ToBase64String(userRace.Image);
                                    var imgSrc = String.Format("data:image/png;base64,{0}", base64);
                                    <tr>
                                        <td>@user.FirstName @user.LastName)</td>
                                        <td>@userRace.Name</td>
                                        <td><img class='raceIcon' src="@imgSrc" /></td>
                                    </tr>
                                }
                            </tbody>

                        </table>

                    </div>
                </div>
            </div>
        </div>
    }
</div>

NeuroshimaHex.Web/Views/Game/SetStatus.cshtml
@model NeuroshimaHex.Web.Models.Game.SetGameStatusViewModel

@{
    ViewBag.Title = "Set Game Status";
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.PanelTitle = "Game " + Model.Name;
    ViewBag.Heading = "Set Game Status";
    var teams = Model.Teams.Select(x => new SelectListItem
    {
        Value = x.Id.ToString(),
        Text = x.TeamName
    });
}
<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <h3>@ViewBag.Title</h3>

        <div class="row">
            <div class="panel panel-section">
                <div class="panel-heading">
                    <h2 class="panel-title">@ViewBag.PanelTitle</h2>
                </div>
                <div class="panel-body">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                        <div class="form-horizontal fixed-inputs">
                            <hr />

                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.Id)
                            <div class="form-group">
                                @Html.LabelFor(model => model.IsFinished, htmlAttributes: new { @class = "control-label col-md-1" })
                                <div class="col-md-10">
                                    @Html.CheckBoxFor(model => model.IsFinished, new { htmlAttributes = new { @class = "form-control game" } })
                                </div>
                            </div>
                            @Html.LabelFor(m => m.WinsTeamGuid)
                            @Html.DropDownListFor(m => m.WinsTeamGuid, teams, new { @class = "form-control", id = "selParent" })
                        </div>
                        <div class="form-group">
                            <div class="col-md-offset-1 col-md-10">
                                <input type="submit" value="Save" class="btn btn-default" />
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

NeuroshimaHex.Web/Views/Game/_CommonEdit.cshtml
@using NeuroshimaHex.Domain.Entities
@using NeuroshimaHex.Web.Models.Game
@using NeuroshimaHex.Web.Models.Team
@model NeuroshimaHex.Web.Models.Game.GameEditViewModel

@{

}
<div class="form-horizontal fixed-inputs">
    <hr />

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.CreatorId)
    @if (Model.GameTime == null || Model.GameTime >= DateTime.Now)
    {
        <div class="form-group">
            @Html.LabelFor(model => model.GameTime, htmlAttributes: new { @class = "control-label col-md-1" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GameTime, new { htmlAttributes = new { @id = "gameTime", @class = "form-control" } })
            </div>
        </div>
    }
    else
    {
        @Html.HiddenFor(model => model.GameTime)
    }
    
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-1" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @Value = ViewBag.DefaultTeamName } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>
    @if (Model.Teams.Count < 1)
    {
        <div class="panel panel-default col-md-7" style="margin-right: 10px; display: inline-block">
            <button type="button" id="createTeamBtn" class="btn btn-success" style="margin: 15px;"
                    data-url='@Url.Action("CreateTeam", "Team")'>
                Add Teams
            </button>
            <div class="form-group">
                <label class="control-label col-md-2" for="TeamCount">Team Count</label>
                <input id="TeamCount" class="form-control text-box single-line valid col-md-10" name="TeamCount" type="number" min="2" value="2">
            </div>
            <div class="form-group">
                <label class="control-label col-md-2" for="TeammateCount">Teammate Count</label>
                <input id="TeammateCount" class="form-control text-box single-line valid c" name="TeammateCount" type="number" min="1" value="1">
            </div>
            <button type="button" id="randomRace" class="btn btn-success hidden" onclick="SetRandomRaces()" style="margin: 15px;">
                 Set Random Races
            </button>
        </div>
    }
    

    <div id="teamsContainer">
        @if (Model.Teams.Count >= 1)
        {
            @Html.Partial("~/Views/Team/_CommonTeamEdit.cshtml", Model)
        }
    </div>

    
    <div class="form-group">
        <div class="col-md-offset-1 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>

</div>


<script>
    $.fn.getUnicOptions = function () {
        var array = [];
        this.each(function () {
            if ($(this).val() != "0") {
                var isNeedToPush = true;
                for (var i = 0; i < array.length; i++) {
                    if (array[i].val() == $(this).val()) {
                        isNeedToPush = false;
                    }
                }
                if (isNeedToPush) {
                    array.push($(this));
                }
            }
        });
        return array;
    }

    $(function() {
        $('#gameTime').datetimepicker({ minDate: moment() });
        $('#gameTime').val("@DateTime.Now.ToString("g")");
    });

    function SetRandomRaces() {
        $(".race option:selected").removeAttr("selected");
        $(".race").trigger("change");
        var uniqOptionsArray = $(".race option").getUnicOptions();
        for (var i = 0; i < $('.race').length; i++) {
            var randomValue = Math.floor(Math.random() * uniqOptionsArray.length);
            $('.race').eq(i).val(uniqOptionsArray[randomValue].val());
            uniqOptionsArray.splice(randomValue, 1);
            $('.race').trigger('change');
        }
        $(".race").change();
    }

    $('#createTeamBtn').on('click', function (evt) {
        evt.preventDefault();
        evt.stopPropagation();
        var teamCount = $("#TeamCount").val();
        var teammateCount = $("#TeammateCount").val();

        var url = $(this).data('url');
        url = url + "?teamCount=" + teamCount + "&teammateCount=" + teammateCount;
        $.get(url, function (data) {
            $('#teamsContainer').html(data);
            $("#randomRace").removeClass("hidden");
        });
    });
</script>