NeuroshimaHex.Web/Models/User/UserEditViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NeuroshimaHex.Web.Models.Race;

namespace NeuroshimaHex.Web.Models.User
{
    public class UserEditViewModel
    {
        public Guid Id { get; set; }

        [Required]
        [Display(Name = "Username")]
        [DataType(DataType.EmailAddress)]
       // [Remote("IsUsernameAvailable", "Validation", AdditionalFields = "Id")]
        public string UserName { get; set; }

        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Display(Name = "Email")]
        [DataType(DataType.EmailAddress)]
       // [Remote("IsEmailAvailable", "Validation", AdditionalFields = "Id")]
        public string Email { get; set; }

        [Display(Name = "Admin Access")]
        public bool IsAdmin { get; set; }

        [Display(Name = "Favorite Race")]
        public Guid? FavoriteRaceId { get; set; }

        public IEnumerable<SelectListItem> RacesSelectList { get; set; }
        public List<RaceViewModel> Races { get; set; }


        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        [MinLength(6)]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm Password")]
        [System.ComponentModel.DataAnnotations.Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }

        [Display(Name = "Change Password")]
        public bool IsChangingPassword { get; set; }

        [Display(Name = "Current Password")]
        [DataType(DataType.Password)]
        [MinLength(6)]
        public string CurrentPassword { get; set; }

        [Display(Name = "New Password")]
        [DataType(DataType.Password)]
        [MinLength(6)]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm Password")]
        [System.ComponentModel.DataAnnotations.Compare("NewPassword", ErrorMessage = "The new password and the new password confirmation do not match.")]
        public string ConfirmNewPassword { get; set; }
    }
}

NeuroshimaHex.Web/Models/User/UserListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using NeuroshimaHex.Web.Models.Shared;

namespace NeuroshimaHex.Web.Models.User
{
    public class UserListViewModel : SearchListViewModel<UserViewModel>
    {
    }
}

NeuroshimaHex.Web/Models/User/UserViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NeuroshimaHex.Web.Models.Race;

namespace NeuroshimaHex.Web.Models.User
{
    public class UserViewModel
    {
        public Guid Id { get; set; }

        [Display(Name = "User Name")]
        public string UserName { get; set; }

        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Display(Name = "User Race")]
        public RaceViewModel Race { get; set; }
      
        public List<UsersInGameViewModel> UsersInGames { get; set; }

        public IEnumerable<SelectListItem> RacesSelectList { get; set; }
        public IEnumerable<SelectListItem> UsersSelectList { get; set; }

    }
}

NeuroshimaHex.Web/Models/User/UsersInGameViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using NeuroshimaHex.Web.Models.Race;

namespace NeuroshimaHex.Web.Models.User
{
    public class UsersInGameViewModel
    {
       // public Guid Id { get; set; }
        public Guid GameId { get; set; }

        public Guid UserId { get; set; }

        public Guid RaceId { get; set; }
    }
}

NeuroshimaHex.Web/Controllers/RaceController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using NeuroshimaHex.Bll.Contracts.Services;
using NeuroshimaHex.Domain.Entities;
using NeuroshimaHex.Domain.Objects.Query;
using NeuroshimaHex.Web.Models.Race;

namespace NeuroshimaHex.Web.Controllers
{
    public class RaceController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IRaceService _raceService;

        public RaceController(IMapper mapper, IRaceService raceService)
        {
            _mapper = mapper;
            _raceService = raceService;
        }

        public ActionResult RaceInfo()
        {
            var model = new RaceInfoViewModel();
            var races = _raceService.GetRaces();
            model.Races = _mapper.Map<List<RaceViewModel>>(races);
            return View("~/Views/Race/RaceInfo.cshtml", model);
        }

        public ActionResult Index(string search = "", int page = 1, int length = 15)
        {
            var result = _raceService.GetRaces(new SearchQuery
            {
                Orderby = new ColumnOrder
                {
                    Column = "Name",
                    Direction = SortDirection.Asc
                },
                Paging = new Paging
                {
                    Length = length,
                    Skip = (page - 1) * length,
                },
                Search = search,
            });
            return View(new RaceListViewModel()
            {
                Search = search,
                Page = page,
                RecordsFiltered = result.RecordsFiltered,
                RecordsTotal = result.RecordsTotal,
                PageNumber = result.RecordsFiltered / length + (result.RecordsFiltered % length > 0 ? 1 : 0),
                Records = result.Data.Select(x => _mapper.Map<RaceViewModel>(x)).ToList()
            });
        }

        public ActionResult Create()
        {
            var model = new RaceEditViewModel();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RaceEditViewModel model)
        {

            if (ModelState.IsValid)
            {
                model.Id = Guid.NewGuid();
                if (model.Image == null)
                {
                    string imageFile = Path.Combine(Server.MapPath("~/Images"), "orc_default.png");
                    byte[] buffer = System.IO.File.ReadAllBytes(imageFile);
                    model.Image = buffer;
                }
                var value = _mapper.Map<Race>(model);
                _raceService.AddRace(value);
                
                return RedirectToAction("Index");
            }
            return View(model);
        }

        public ActionResult Edit(Guid id)
        {
            var value = _raceService.GetRaceById(id);
            var model = _mapper.Map<RaceEditViewModel>(value);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(RaceEditViewModel model)
        {
            var value = _raceService.GetRaceById(model.Id);
            if (value != null)
            {
                _mapper.Map(model, value);
                _raceService.UpdateRace(value);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Remove(RaceEditViewModel model)
        {
            var value = _raceService.GetRaceById(model.Id);
            if (value != null)
            {
                _raceService.ToArchive(value);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Statistic(DateTime? dateFrom, DateTime? dateTo)
        {
            var model = new RacesStatisticViewModel();
            var wonRacesId = _raceService.GetWonRacesId(new SearchQuery
            {
                DateFrom = dateFrom,
                DateTo = dateTo
            });
            var values = _raceService.GetRaces();
            var races = _mapper.Map<List<RaceViewModel>>(values);
            foreach (var raceid in wonRacesId.Distinct())
            {
                var race = races.Single(r => r.Id == raceid);
                var wonCount = wonRacesId.Count(x => x == raceid);
                model.Statistic.Add(new RaceStatisticModel { Race = race, WonCount = wonCount });

            }
            return View("~/Views/Race/Statistic.cshtml",model);
        }
    }
}

NeuroshimaHex.Web/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using Microsoft.AspNet.Identity;
using NeuroshimaHex.Bll.Contracts.Services;
using NeuroshimaHex.Bll.Services.Identity;
using NeuroshimaHex.Domain.Entities;
using NeuroshimaHex.Domain.Enums;
using NeuroshimaHex.Domain.Objects.Query;
using NeuroshimaHex.Web.Attributes;
using NeuroshimaHex.Web.Extensions;
using NeuroshimaHex.Web.Models.Race;
using NeuroshimaHex.Web.Models.User;

namespace NeuroshimaHex.Web.Controllers
{
    public class UserController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IUserService _userService;
        private readonly IRaceService _raceService;
        private readonly NeuroshimaHexUserManager _userManager;


        public UserController(IMapper mapper, IUserService userService, IRaceService raceService, NeuroshimaHexUserManager userManager)
        {
            _mapper = mapper;
            _userService = userService;
            _raceService = raceService;
            _userManager = userManager;
        }

        public ActionResult GetUsers(string search = "", int page = 1, int length = 15)
        {
            var result = _userService.GetUsers(new SearchQuery
            {
                Orderby = new ColumnOrder
                {
                    Column = "UserName",
                    Direction = SortDirection.Asc
                },
                Paging = new Paging
                {
                    Length = length,
                    Skip = (page - 1) * length,
                },
                Search = search,
            });
            return View("~/Views/User/GetUsers.cshtml",new UserListViewModel()
            {
                Search = search,
                Page = page,
                RecordsFiltered = result.RecordsFiltered,
                RecordsTotal = result.RecordsTotal,
                PageNumber = result.RecordsFiltered / length + (result.RecordsFiltered % length > 0 ? 1 : 0),
                Records = result.Data.Select(x => _mapper.Map<UserViewModel>(x)).ToList()
            });
        }

        public ActionResult Create()
        {
            var model = new UserEditViewModel();
            var races = _raceService.GetRaces();
            model.Races = _mapper.Map<List<RaceViewModel>>(races);
            var defaultSelectItem = new SelectListItem { Text = "Select", Value = "0", Selected = true, Disabled = true };
            var racesListItem = model.Races.Select(r => new SelectListItem
            {
                Text = r.Name,
                Value = r.Id.ToString(),
            }).ToList();
            racesListItem.Add(defaultSelectItem);
            model.RacesSelectList = racesListItem;
            return View("~/Views/User/Create.cshtml",model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(UserEditViewModel model)
        {
            var user = _userManager.FindById(model.Id);
            if (user == null)
            {
                user = _mapper.Map<User>(model);
                user.CreatedAt = DateTime.UtcNow;
                user.LastModifiedAt = DateTime.UtcNow;
                var result = _userManager.Create(user, model.Password);

                if (result.Succeeded && model.IsAdmin)
                {
                    _userManager.AddToRole(user.Id, UserRoles.Admin);
                }
            }
            return RedirectToAction("GetUsers");
        }

        [OverrideAuthorize()]
        public ActionResult Edit(Guid id, string returnUrl = null)
        {
            ViewBag.ReturnUrl = returnUrl;
            var value = _userService.GetById(id);
            ViewBag.ReturnUrl = returnUrl == null ? Url.Action("GetUsers", "User") : returnUrl;
            var model = _mapper.Map<UserEditViewModel>(value);
            model.IsAdmin = _userService.IsAdmin(id);

            var races = _raceService.GetRaces();
            model.Races = _mapper.Map<List<RaceViewModel>>(races);
            var emptySelectItem = new SelectListItem { Text = "  ", Selected = !model.FavoriteRaceId.HasValue };
            var racesListItem = model.Races.Select(r => new SelectListItem
            {
                Text = r.Name,
                Value = r.Id.ToString(),
                Selected = r.Id == model.FavoriteRaceId
            }).ToList();
            racesListItem.Add(emptySelectItem);
            model.RacesSelectList = racesListItem;

            return View("~/Views/User/Edit.cshtml", model);
        }

        public ActionResult Archive(Guid id)
        {
            _userService.ToArchive(id);
            return RedirectToAction("GetUsers");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(UserEditViewModel model, string returnUrl = null)
        {
            var user = _userService.GetById(model.Id);
            if (user == null || !ModelState.IsValid)
                return View(model);

            _mapper.Map(model, user);
            _userService.Update(user);

            if (model.IsAdmin)
            {
                _userService.AddRole(user, UserRoles.Admin);
            }
            else
            {
                _userService.RemoveRole(user, UserRoles.Admin);
            }

            if (model.IsChangingPassword)
            {
                var result = _userManager.ChangePassword(user.Id, model.CurrentPassword, model.NewPassword);
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("CurrentPassword", string.Join(",", result.Errors));
                    return View(model);
                }
            }

            if (returnUrl != null)
                return Redirect(returnUrl);

            return RedirectToAction("GetUsers");
        }

    }
}

NeuroshimaHex.Web/Views/User/Create.cshtml
@model NeuroshimaHex.Web.Models.User.UserEditViewModel

@{
    ViewBag.Title = "Create User";
    Layout = "~/Views/User/_CommonEditLayout.cshtml";
    ViewBag.PanelTitle = "Main Information";
    ViewBag.Heading = "Create User";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.Partial("_CommonEdit")
}

NeuroshimaHex.Web/Views/User/Edit.cshtml
@model NeuroshimaHex.Web.Models.User.UserEditViewModel

@{
    ViewBag.Title = "Edit User";
    Layout = "~/Views/User/_CommonEditLayout.cshtml";
    ViewBag.PanelTitle = "User";
    ViewBag.Heading = "Edit User";
}

@using (Html.BeginForm("Edit", "User", new { returnUrl = ViewBag.ReturnUrl }, FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.Partial("_CommonEdit")
}

NeuroshimaHex.Web/Views/User/GetUsers.cshtml
@using NeuroshimaHex.Web.Models
@model NeuroshimaHex.Web.Models.User.UserListViewModel

@{
    ViewBag.Title = NavigationItems.Users; 
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Partial("~/Views/Shared/_DeletionConfirmationModalPartial.cshtml", new NeuroshimaHex.Web.Models.Shared.SharedModalViewModel
{
    ConfirmActionUrl = "",
    Message = "this user",
    AdditionalInformation = "<p>This will delete all the initiatives created by this user.</p>"
})

<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <div class="row">
            <h3>@ViewBag.Title</h3>

            <div>
                @Html.ActionLink("Add", "Create", null, new { @class = "btn btn-default", style = "float: left; display: inline-block; margin-top: 8px" })
            </div>

            <form class="navbar-form navbar-left" role="search">
                @Html.TextBoxFor(m => m.Search, new { @class = "form-control", placeholder = "Search" })
                <button type="submit" class="btn btn-default">Submit</button>
            </form>

        </div>
        <div class="row">
            <div class="panel panel-section">
                <div class="panel-heading">
                    <h2 class="panel-title">List of Users</h2>
                </div>
                <div class="panel-body">
                    <table class="table table-striped table-bordered table-hover" style="margin-top: 15px;">
                        <tr>
                            <th>
                                @Html.DisplayName("Username")
                            </th>
                            <th>
                                @Html.DisplayName("First Name")
                            </th>
                            <th>
                                @Html.DisplayName("Last Name")
                            </th>
                            <th>
                                @Html.DisplayName("Action")
                            </th>
                        </tr>

                        @foreach (var item in Model.Records)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.UserName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.FirstName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.LastName)
                                </td>
                                <td>
                                    @Html.ActionLink("Edit", "Edit", new { id = item.Id })
                                    @Html.Raw("/")
                                    <a href="#" onclick="deleteUser('@Url.Action("Archive", new { id = item.Id })')">Archive</a>
                                </td>
                            </tr>
                        }
                    </table>

                    @Html.Partial("~/Views/Shared/_PaginationPartial.cshtml", Model)
                </div>
            </div>
        </div>
    </div>
</div>
<hr />

@section scripts {
    <script>
        var deleteUser = function (url) {
            $('#deletionConfirmationModalConfirmButton').prop('href', url);
            $('#deletionConfirmationModal').modal('show');
        }
    </script>
}

NeuroshimaHex.Web/Views/User/_CommonEdit.cshtml
@using NeuroshimaHex.Web.Extensions
@model NeuroshimaHex.Web.Models.User.UserEditViewModel

@{
    string returnUrl = ViewBag.ReturnUrl == null ? Url.Action("RaceInfo", "Race") : ViewBag.ReturnUrl;
}

<div class="form-horizontal fixed-inputs">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    <div class="form-group">
        @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-1" })
        <div class="col-md-10">
            @if (Model.Id == new Guid())
            {
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
            }
            else
            {
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
            }
            @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-1" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-1" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
        </div>
    </div>
    
    <div class="form-group">
        @Html.LabelFor(model => model.FavoriteRaceId, htmlAttributes: new { @class = "control-label col-md-1" })
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.FavoriteRaceId, Model.RacesSelectList, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-1" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IsAdmin, htmlAttributes: new { @class = "control-label col-md-1" })
        <div class="col-md-10 checkbox-green">
            @Html.EditorFor(model => model.IsAdmin, new { @id = "IsAdmin" })
            <label for="IsAdmin" style="margin-top: 5px"></label>
            @Html.ValidationMessageFor(model => model.IsAdmin, "", new { @class = "text-danger" })
        </div>
    </div>

    @if (Model.Id == new Guid())
    {
        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-1" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-1" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>
    }
    else if (Model.Id == User.Identity.GetUserIdGuid())
    {
        <div class="form-group">
            @Html.LabelFor(model => model.IsChangingPassword, htmlAttributes: new { @class = "control-label col-md-1" })
            <div class="col-md-10 checkbox-green">
                @Html.EditorFor(model => model.IsChangingPassword, new { @id = "IsChangingPassword" })
                <label for="IsChangingPassword" style="margin-top: 10px"></label>
                @Html.ValidationMessageFor(model => model.IsChangingPassword, "", new { @class = "text-danger" })
            </div>
        </div>
        <div id="newPassConfirm" style="display: @(Model.IsChangingPassword ? "block" : "none")">
            <div class="form-group">
                @Html.LabelFor(model => model.CurrentPassword, htmlAttributes: new { @class = "control-label col-md-1" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CurrentPassword, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CurrentPassword, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.NewPassword, htmlAttributes: new { @class = "control-label col-md-1" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NewPassword, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NewPassword, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ConfirmNewPassword, htmlAttributes: new { @class = "control-label col-md-1" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ConfirmNewPassword, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ConfirmNewPassword, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    }

    <div class="form-group">
        <div class="col-md-offset-1 col-md-10">
            <input type="submit" value="Save" class="btn btn-success" />
            <a href="@returnUrl" class="btn btn-danger">Cancel</a>
        </div>
    </div>
</div>

NeuroshimaHex.Web/Views/User/_CommonEditLayout.cshtml
@using NeuroshimaHex.Domain.Enums
@model NeuroshimaHex.Web.Models.User.UserEditViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    string panelTitle = ViewBag.PanelTitle;
    string header = ViewBag.Heading;
       

    bool hasBackToList = ViewBag.ReturnUrl == Url.Action("GetUsers", "User");
}

<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <h3>@header</h3>

        <div class="panel panel-section">
            <div class="panel-heading">
                <h3 class="panel-title">@panelTitle</h3>
            </div>
            <div class="panel-body">
                @RenderBody()
            </div>
        </div>
        @if (hasBackToList)
        {
            <br />
            <div>
                @Html.ActionLink("Back to List", "Index")
            </div>
        }

    </div>
</div>

@section scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        var isChangingPassCheckBox = $('#IsChangingPassword');
        if (isChangingPassCheckBox !== undefined) {
            var newPassSection = $('#newPassConfirm');
            isChangingPassCheckBox.on('change', function () {
                console.log(isChangingPassCheckBox.val());
                if (isChangingPassCheckBox.prop('checked') === true) {
                    newPassSection.css('display', 'block');
                } else {
                    newPassSection.css('display', 'none');
                }
            })
        }
    </script>
}